# Generated by Django 5.2.4 on 2025-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('response_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پاسخ')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='پیام پاسخ')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره مرجع')),
                ('terminal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ترمینال')),
            ],
            options={
                'verbose_name': 'تراکنش پوز',
                'verbose_name_plural': 'تراکنش\u200cهای پوز',
            },
        ),
    ]
