# Generated by Django 5.2.4 on 2025-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'تراکنش پوز', 'verbose_name_plural': 'تراکنش\u200cهای پوز'},
        ),
        migrations.AddField(
            model_name='postransaction',
            name='raw_request',
            field=models.TextField(blank=True, null=True, verbose_name='درخواست خام'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='raw_response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ خام'),
        ),
    ]
