# Generated by Django 5.2.4 on 2025-09-13 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_paymentmethod'),
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrosh',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_app.paymentmethod', verbose_name='روش پرداخت'),
        ),
    ]
