# Generated by Django 5.2.4 on 2025-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_invoicefrosh_is_paid_invoicefrosh_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrosh',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خریدار'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن خریدار'),
        ),
        migrations.AddField(
            model_name='invoiceitemfrosh',
            name='standard_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت معیار'),
        ),
    ]
