# Generated by Django 5.2.4 on 2025-09-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_invoicefrosh_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روش پرداخت')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('installment', 'نسیه')], max_length=20, verbose_name='نوع پرداخت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('account_number', models.CharField(max_length=20, verbose_name='شماره حساب')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دستگاه پوز',
                'verbose_name_plural': 'دستگاه\u200cهای پوز',
            },
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='final_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='serial_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='شماره سریال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitemfrosh',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.CreateModel(
            name='CheckPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام صاحب چک')),
                ('owner_family', models.CharField(max_length=100, verbose_name='نام خانوادگی صاحب چک')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('check_number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('check_amount', models.PositiveIntegerField(verbose_name='مبلغ چک')),
                ('check_date', models.DateField(verbose_name='تاریخ چک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoicefrosh', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت چکی',
                'verbose_name_plural': 'پرداخت\u200cهای چکی',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام')),
                ('customer_family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoicefrosh', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت نسیه',
                'verbose_name_plural': 'پرداخت\u200cهای نسیه',
            },
        ),
        migrations.AlterField(
            model_name='invoicefrosh',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.paymentmethod', verbose_name='روش پرداخت'),
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.posdevice', verbose_name='دستگاه پوز')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoicefrosh', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت با پوز',
                'verbose_name_plural': 'پرداخت\u200cهای با پوز',
            },
        ),
    ]
