# Generated by Django 5.2.4 on 2025-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_paymentmethod_posdevice_invoicefrosh_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefrosh',
            name='serial_number',
            field=models.CharField(max_length=36, unique=True, verbose_name='شماره سریال'),
        ),
    ]
