# Generated by Django 5.2.4 on 2025-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_alter_invoicefrosh_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefrosh',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره سریال'),
        ),
    ]
