# Generated by Django 5.2.4 on 2025-09-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_alter_invoicefrosh_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefrosh',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='pos', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.RemoveField(
            model_name='pospayment',
            name='device',
        ),
        migrations.RemoveField(
            model_name='pospayment',
            name='invoice',
        ),
        migrations.AlterModelOptions(
            name='checkpayment',
            options={'verbose_name': 'پرداخت چک', 'verbose_name_plural': 'پرداخت\u200cهای چک'},
        ),
        migrations.RenameField(
            model_name='checkpayment',
            old_name='check_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='checkpayment',
            old_name='national_code',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='posdevice',
            old_name='owner_name',
            new_name='account_holder',
        ),
        migrations.RemoveField(
            model_name='invoicefrosh',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoicefrosh',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitemfrosh',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='pos_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.posdevice', verbose_name='دستگاه پوز'),
        ),
        migrations.AddField(
            model_name='invoicefrosh',
            name='total_without_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ بدون تخفیف'),
        ),
        migrations.AddField(
            model_name='invoiceitemfrosh',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='checkpayment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_payment', to='invoice_app.invoicefrosh'),
        ),
        migrations.AlterField(
            model_name='invoicefrosh',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره سریال'),
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام')),
                ('customer_family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_payment', to='invoice_app.invoicefrosh')),
            ],
            options={
                'verbose_name': 'پرداخت نسیه',
                'verbose_name_plural': 'پرداخت\u200cهای نسیه',
            },
        ),
        migrations.DeleteModel(
            name='InstallmentPayment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='POSPayment',
        ),
    ]
