# Generated by Django 5.2.4 on 2025-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_alter_invoicefrosh_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpayment',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ باقیمانده'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='remaining_payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='cash', max_length=10, verbose_name='روش پرداخت باقیمانده'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ باقیمانده'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='remaining_payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='cash', max_length=10, verbose_name='روش پرداخت باقیمانده'),
        ),
    ]
