# Generated by Django 5.2.4 on 2025-10-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_checkpayment_remaining_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpayment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='remaining_payment_method',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_payment_method',
        ),
    ]
