# Generated by Django 5.2.4 on 2025-10-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0010_alter_checkpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'verbose_name': 'پرداخت نسیه', 'verbose_name_plural': 'پرداخت\u200cهای نسیه'},
        ),
    ]
