# Generated by Django 5.2.4 on 2025-10-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0012_creditpayment_initial_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='initial_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='pos_device',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_payment_method',
        ),
    ]
