# Generated by Django 5.2.4 on 2025-10-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0014_alter_creditpayment_options_creditpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpayment',
            options={},
        ),
        migrations.RenameField(
            model_name='creditpayment',
            old_name='amount',
            new_name='credit_amount',
        ),
    ]
