# Generated by Django 5.2.4 on 2025-10-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0015_alter_creditpayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='pos_device',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='remaining_payment_method',
        ),
    ]
