# Generated by Django 5.2.4 on 2025-10-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0016_remove_creditpayment_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='credit_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ نسیه'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='pos_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.posdevice', verbose_name='دستگاه پوز برای باقیمانده'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ باقیمانده'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='remaining_payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='cash', max_length=10, verbose_name='روش پرداخت باقیمانده'),
        ),
    ]
