# Generated by Django 5.2.4 on 2025-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0017_creditpayment_credit_amount_creditpayment_pos_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrosh',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده'),
        ),
    ]
