# Generated by Django 5.2.4 on 2025-10-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0018_invoicefrosh_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.157', verbose_name='آدرس IP'),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='port',
            field=models.IntegerField(default=1362, verbose_name='پورت'),
        ),
    ]
