# Generated by Django 5.2.4 on 2025-10-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0010_branch_modem_ip'),
        ('invoice_app', '0019_posdevice_ip_address_posdevice_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rial', models.BigIntegerField(verbose_name='مبلغ به ریال')),
                ('pos_ip', models.CharField(max_length=20, verbose_name='IP دستگاه پوز')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='پیام نتیجه')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch')),
            ],
            options={
                'verbose_name': 'تراکنش پوز',
                'verbose_name_plural': 'تراکنش\u200cهای پوز',
                'ordering': ['-created_at'],
            },
        ),
    ]
