# Generated by Django 5.2.4 on 2025-10-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0020_postransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POSTransaction',
        ),
    ]
