# Generated by Django 4.1.7 on 2024-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuntmodel',
            name='phonnumber',
            field=models.CharField(default='0', max_length=11, null=True),
        ),
    ]
