# Generated by Django 4.1.7 on 2025-04-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0003_alter_dataacont_berthday_alter_dataacont_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='عکس پروفایل'),
        ),
    ]
