# Generated by Django 4.1.7 on 2025-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0004_accuntmodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='savecodphon',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='عکس پروفایل'),
        ),
    ]
