# Generated by Django 4.1.7 on 2025-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0005_savecodphon_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecodphon',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default/def.jpg', null=True, upload_to='profile_pics/', verbose_name='عکس پروفایل'),
        ),
    ]
