# Generated by Django 4.1.7 on 2025-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0006_alter_savecodphon_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuntmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='savecodphon',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
