# Generated by Django 4.1.7 on 2025-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0007_alter_accuntmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuntmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='savecodphon',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicstest/'),
        ),
    ]
