# Generated by Django 5.2.4 on 2025-08-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0008_alter_accuntmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('address', models.TextField(verbose_name='آدرس شعبه')),
                ('sellers', models.ManyToManyField(blank=True, to='cantact_app.accuntmodel', verbose_name='فروشندگان')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
            },
        ),
        migrations.CreateModel(
            name='BranchAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='مدیر شعبه')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'مدیر شعبه',
                'verbose_name_plural': 'مدیران شعب',
            },
        ),
    ]
