# Generated by Django 5.2.4 on 2025-10-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0009_branch_branchadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='modem_ip',
            field=models.GenericIPAddressField(blank=True, help_text='آدرس IP مودم شعبه', null=True, verbose_name='IP مودم'),
        ),
    ]
