# Generated by Django 5.2.4 on 2025-08-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['item_number']},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='تصویر بارکد'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مقدار بارکد'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_number',
            field=models.PositiveIntegerField(default=0, verbose_name='شماره کالا'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت فروش'),
        ),
    ]
