# Generated by Django 5.2.4 on 2025-08-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0002_alter_invoiceitem_options_remove_invoiceitem_barcode_and_more'),
    ]

    operations = [
    ]
