# Generated by Django 5.2.4 on 2025-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0003_auto_20250814_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='نام جستجو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='نام کالا'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='dashbord_ap_name_6eb9af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_name'], name='dashbord_ap_search__9330b5_idx'),
        ),
    ]
