# Generated by Django 5.2.4 on 2025-08-15 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0004_remove_product_barcode_product_search_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='dashbord_ap_name_6eb9af_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='dashbord_ap_search__9330b5_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_name',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='بارکد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام کالا'),
        ),
    ]
