# Generated by Django 5.2.4 on 2025-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0005_remove_product_dashbord_ap_name_6eb9af_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='froshande',
            options={'ordering': ['family', 'name'], 'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.AlterField(
            model_name='froshande',
            name='address',
            field=models.TextField(blank=True, help_text='آدرس کامل فروشنده', null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='card_number',
            field=models.CharField(blank=True, help_text='شماره کارت بانکی ۱۶ رقمی', max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='family',
            field=models.CharField(help_text='نام خانوادگی فروشنده را وارد کنید', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='mobile',
            field=models.CharField(help_text='شماره همراه ۱۱ رقمی', max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='name',
            field=models.CharField(help_text='نام فروشنده را وارد کنید', max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تلفن ثابت با پیش\u200cشماره', max_length=11, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='sheba_number',
            field=models.CharField(help_text='شماره شبا بانکی ۲۶ رقمی', max_length=26, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='store_name',
            field=models.CharField(blank=True, help_text='نام فروشگاه یا کسب و کار', max_length=200, null=True, verbose_name='اسم فروشگاه'),
        ),
        migrations.AlterField(
            model_name='froshande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddIndex(
            model_name='froshande',
            index=models.Index(fields=['name', 'family'], name='dashbord_ap_name_70ec31_idx'),
        ),
        migrations.AddIndex(
            model_name='froshande',
            index=models.Index(fields=['store_name'], name='dashbord_ap_store_n_85f74e_idx'),
        ),
        migrations.AddIndex(
            model_name='froshande',
            index=models.Index(fields=['mobile'], name='dashbord_ap_mobile_ba1611_idx'),
        ),
        migrations.AddIndex(
            model_name='froshande',
            index=models.Index(fields=['card_number'], name='dashbord_ap_card_nu_d714bf_idx'),
        ),
        migrations.AddIndex(
            model_name='froshande',
            index=models.Index(fields=['sheba_number'], name='dashbord_ap_sheba_n_14ac96_idx'),
        ),
        migrations.AddConstraint(
            model_name='froshande',
            constraint=models.UniqueConstraint(fields=('mobile',), name='unique_mobile'),
        ),
        migrations.AddConstraint(
            model_name='froshande',
            constraint=models.UniqueConstraint(fields=('sheba_number',), name='unique_sheba'),
        ),
    ]
