# Generated by Django 5.2.4 on 2025-08-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0006_alter_froshande_options_alter_froshande_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode_value',
        ),
    ]
