# Generated by Django 5.2.4 on 2025-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0007_remove_invoiceitem_barcode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفیف (%)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='محل چیدن جنس'),
        ),
    ]
