# Generated by Django 5.2.4 on 2025-08-22 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0008_invoiceitem_discount_invoiceitem_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سریال')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فاکتور')),
                ('operator', models.CharField(default='علی اسدپور', max_length=100, verbose_name='اپراتور')),
                ('branch', models.CharField(default='نیشابور', max_length=100, verbose_name='شعبه')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع کل')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع تخفیف')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قابل پرداخت')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='بارکد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت واحد')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت فروش')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفیف (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ تخفیف')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='جمع ردیف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashbord_app.saleinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord_app.product')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور فروش',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور فروش',
            },
        ),
    ]
