# Generated by Django 5.2.4 on 2025-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0009_saleinvoice_saleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عدد بارکد'),
        ),
    ]
