# Generated by Django 5.2.4 on 2025-08-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0010_alter_invoiceitem_options_invoiceitem_barcode_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['item_number']},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode_number',
        ),
        migrations.DeleteModel(
            name='SaleInvoice',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
