# Generated by Django 5.2.4 on 2025-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0011_remove_saleitem_invoice_remove_saleitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['item_number'], 'verbose_name': 'آیتم فاکتور', 'verbose_name_plural': 'آیتم های فاکتور'},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع کل قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف (تومان)'),
        ),
    ]
