# Generated by Django 5.2.4 on 2025-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0013_alter_invoiceitem_options_invoiceitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode_base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
