# Generated by Django 5.2.4 on 2025-08-28 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0014_invoiceitem_barcode_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['item_number'], 'verbose_name': 'آیتم فاکتور', 'verbose_name_plural': 'آیتم های فاکتور'},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='barcode_base',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_number',
            field=models.PositiveIntegerField(default=0, verbose_name='شماره کالا'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='کالای نامشخص', max_length=200, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت واحد'),
        ),
    ]
