# Generated by Django 5.2.4 on 2025-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0015_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_payable',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='محل چیدن جنس'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفیف (%)'),
        ),
    ]
