# Generated by Django 5.2.4 on 2025-08-30 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0016_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره حساب')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('is_primary', models.BooleanField(default=False, verbose_name='حساب اصلی')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('mobile', 'تلفن همراه'), ('phone', 'تلفن ثابت')], max_length=10, verbose_name='نوع تماس')),
                ('number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('is_primary', models.BooleanField(default=False, verbose_name='شماره اصلی')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
        migrations.RemoveConstraint(
            model_name='froshande',
            name='unique_mobile',
        ),
        migrations.RemoveConstraint(
            model_name='froshande',
            name='unique_sheba',
        ),
        migrations.RemoveIndex(
            model_name='froshande',
            name='dashbord_ap_mobile_ba1611_idx',
        ),
        migrations.RemoveIndex(
            model_name='froshande',
            name='dashbord_ap_card_nu_d714bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='froshande',
            name='dashbord_ap_sheba_n_14ac96_idx',
        ),
        migrations.RemoveField(
            model_name='froshande',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='froshande',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='froshande',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='froshande',
            name='sheba_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='froshande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='dashbord_app.froshande', verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='froshande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='dashbord_app.froshande', verbose_name='فروشنده'),
        ),
        migrations.AddConstraint(
            model_name='contactnumber',
            constraint=models.UniqueConstraint(fields=('froshande', 'number'), name='unique_contact_per_froshande'),
        ),
    ]
