# Generated by Django 5.2.4 on 2025-09-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0018_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
