# Generated by Django 5.2.4 on 2025-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0019_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='anbar',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی در زمان فروش'),
        ),
    ]
