# Generated by Django 5.2.4 on 2025-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0020_invoiceitem_anbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='anbar',
            field=models.PositiveIntegerField(default=0, verbose_name='منتقل شده به انبار'),
        ),
    ]
