# Generated by Django 5.2.4 on 2025-09-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0021_alter_invoiceitem_anbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='anbar',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='selling_price',
        ),
    ]
