# Generated by Django 5.2.4 on 2025-09-05 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0022_remove_invoiceitem_anbar_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='anbar',
            field=models.PositiveIntegerField(default=0, verbose_name='منتقل شده به انبار'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashbord_app.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord_app.product'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='کالای نامشخص', max_length=200, verbose_name='نام کالا'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت فروش'),
        ),
    ]
