# Generated by Django 5.2.4 on 2025-09-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0023_invoiceitem_anbar_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='anbar',
        ),
    ]
