# Generated by Django 5.2.4 on 2025-09-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0024_remove_invoiceitem_anbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='remaining_quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد باقیمانده'),
        ),
    ]
