# Generated by Django 5.2.4 on 2025-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0025_remove_invoiceitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_number',
            field=models.IntegerField(default=1, verbose_name='شماره آیتم'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت فروش'),
        ),
    ]
