# Generated by Django 5.2.4 on 2025-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0026_invoiceitem_discount_invoiceitem_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_type',
            field=models.CharField(default='جدید', max_length=10, verbose_name='نوع کالا'),
        ),
    ]
