# Generated by Django 5.2.4 on 2025-09-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0027_invoiceitem_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_type',
        ),
    ]
