# Generated by Django 5.2.4 on 2025-09-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0028_remove_invoiceitem_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(max_length=100, unique=True, verbose_name='نوع لیبل')),
                ('copies_count', models.PositiveIntegerField(default=1, verbose_name='تعداد چاپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیم چاپ لیبل',
                'verbose_name_plural': 'تنظیمات چاپ لیبل',
            },
        ),
    ]
