# Generated by Django 5.2.4 on 2025-09-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0029_labelprintsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelPrintSetting',
        ),
    ]
