# Generated by Django 5.2.4 on 2025-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0030_delete_labelprintsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_type',
            field=models.CharField(choices=[('new', 'کالای جدید'), ('old', 'کالای قدیمی')], default='new', max_length=10, verbose_name='نوع کالا'),
        ),
    ]
