# Generated by Django 5.2.4 on 2025-09-14 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord_app', '0031_invoiceitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ صدور'),
        ),
    ]
