# Generated by Django 5.2.4 on 2025-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('product', 'محصولات'), ('invoice', 'فاکتورها'), ('customer', 'مشتریان'), ('pos', 'تراکنش\u200cهای پوز'), ('stock', 'موجودی انبار'), ('user', 'کاربران'), ('branch', 'شعبه\u200cها'), ('expense', 'هزینه\u200cها')], max_length=20)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('source_ip', models.GenericIPAddressField()),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'server_sync_log',
            },
        ),
        migrations.CreateModel(
            name='SyncToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.TextField(help_text='IPهای مجاز (هر خط یک IP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_tokens',
            },
        ),
    ]
