# Generated by Django 5.2.4 on 2025-11-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerSyncLog',
        ),
        migrations.DeleteModel(
            name='SyncToken',
        ),
    ]
