# Generated by Django 5.2.4 on 2025-10-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True, verbose_name='کلید تنظیم')),
                ('setting_value', models.TextField(verbose_name='مقدار تنظیم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='آخرین همگام\u200cسازی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات آفلاین',
                'verbose_name_plural': 'تنظیمات آفلاین',
                'db_table': 'offline_settings',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('record_id', models.IntegerField(verbose_name='آیدی رکورد')),
                ('action', models.CharField(max_length=10, verbose_name='عمل')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='داده')),
                ('sync_status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت همگام\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ همگام\u200cسازی')),
                ('error_message', models.TextField(blank=True, verbose_name='پیغام خطا')),
            ],
            options={
                'verbose_name': 'لاگ همگام\u200cسازی',
                'verbose_name_plural': 'لاگ\u200cهای همگام\u200cسازی',
                'db_table': 'sync_log',
            },
        ),
    ]
