# Generated by Django 5.2.4 on 2025-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('product', 'محصولات'), ('invoice', 'فاکتورها'), ('customer', 'مشتریان'), ('pos', 'تراکنش\u200cهای پوز')], max_length=20)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'data_sync_log',
            },
        ),
        migrations.DeleteModel(
            name='SyncLog',
        ),
        migrations.AlterModelOptions(
            name='offlinesetting',
            options={},
        ),
        migrations.AlterField(
            model_name='offlinesetting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offlinesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offlinesetting',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offlinesetting',
            name='setting_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='offlinesetting',
            name='setting_value',
            field=models.TextField(),
        ),
    ]
