# Generated by Django 5.2.4 on 2025-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0002_datasynclog_delete_synclog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], max_length=20)),
                ('status', models.CharField(default='in_progress', max_length=20)),
            ],
            options={
                'db_table': 'sync_sessions',
            },
        ),
        migrations.AlterModelOptions(
            name='offlinesetting',
            options={'verbose_name': 'تنظیمات آفلاین', 'verbose_name_plural': 'تنظیمات آفلاین'},
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='conflict_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='sync_direction',
            field=models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], default='local_to_server', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasynclog',
            name='model_type',
            field=models.CharField(choices=[('product', 'محصولات'), ('invoice', 'فاکتورها'), ('customer', 'مشتریان'), ('pos', 'تراکنش\u200cهای پوز'), ('stock', 'موجودی انبار')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['sync_status', 'model_type'], name='data_sync_l_sync_st_da996f_idx'),
        ),
    ]
