# Generated by Django 5.2.4 on 2025-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0003_syncsession_alter_offlinesetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('source_ip', models.GenericIPAddressField()),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('app_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'server_sync_log',
            },
        ),
        migrations.AlterModelOptions(
            name='datasynclog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='syncsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='app_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='model_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offlinesetting',
            name='data_type',
            field=models.CharField(choices=[('string', 'متنی'), ('integer', 'عددی'), ('boolean', 'بولین'), ('json', 'JSON')], default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='records_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='sync_type',
            field=models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی'), ('forced', 'اجباری')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasynclog',
            name='model_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasynclog',
            name='record_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='syncsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('partial', 'ناقص')], default='in_progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['app_name', 'model_name'], name='data_sync_l_app_nam_823676_idx'),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['created_at'], name='data_sync_l_created_58aa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='serversynclog',
            index=models.Index(fields=['processed', 'created_at'], name='server_sync_process_7f244c_idx'),
        ),
    ]
