# Generated by Django 5.2.4 on 2025-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0004_serversynclog_alter_datasynclog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasynclog',
            name='batch_id',
            field=models.CharField(blank=True, help_text='شناسه دسته برای ردیابی', max_length=100),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='is_full_sync',
            field=models.BooleanField(default=False, help_text='آیا سینک کامل بوده است؟'),
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='last_sync_timestamp',
            field=models.DateTimeField(blank=True, help_text='آخرین زمان سینک موفق', null=True),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['last_sync_timestamp', 'model_type'], name='data_sync_l_last_sy_c99b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['batch_id'], name='data_sync_l_batch_i_6bd50d_idx'),
        ),
    ]
