# Generated by Django 5.2.4 on 2025-09-01 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantact_app', '0009_branch_branchadmin'),
        ('dashbord_app', '0017_bankaccount_contactnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد موجودی')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbord_app.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی\u200cهای انبار',
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
