# Generated by Django 5.2.4 on 2025-09-09 10:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantact_app', '0009_branch_branchadmin'),
        ('dashbord_app', '0024_remove_invoiceitem_anbar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='مبلغ پرداخت شده')),
                ('status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partially_paid', 'تا اندازه ای پرداخت شده'), ('settled', 'تسویه حساب')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_document', to='dashbord_app.invoice')),
            ],
            options={
                'verbose_name': 'سند مالی',
                'verbose_name_plural': 'اسناد مالی',
            },
        ),
        migrations.CreateModel(
            name='FinancialDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='تخفیف (%)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت کل')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account_app.financialdocument')),
            ],
            options={
                'verbose_name': 'آیتم سند مالی',
                'verbose_name_plural': 'آیتم\u200cهای سند مالی',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('is_new', models.BooleanField(default=True, verbose_name='کالای جدید')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('count_date', models.CharField(default='', max_length=10, verbose_name='تاریخ شمارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شمارنده')),
            ],
            options={
                'verbose_name': 'شمارش انبار',
                'verbose_name_plural': 'شمارش های انبار',
                'ordering': ['-created_at'],
            },
        ),
    ]
