# Generated by Django 5.2.4 on 2025-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
