# Generated by Django 5.2.4 on 2025-09-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('cantact_app', '0009_branch_branchadmin'),
        ('dashbord_app', '0017_bankaccount_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه'),
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('action', models.CharField(choices=[('add', 'افزودن موجودی'), ('remove', 'کاهش موجودی'), ('transfer', 'انتقال بین شعب')], max_length=10, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='cantact_app.branch', verbose_name='از شعبه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbord_app.product', verbose_name='کالا')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='cantact_app.branch', verbose_name='به شعبه')),
            ],
            options={
                'verbose_name': 'تاریخچه موجودی',
                'verbose_name_plural': 'تاریخچه موجودی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
