# Generated by Django 5.2.4 on 2025-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_inventorycount_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='داده بارکد'),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='کالای جدید'),
        ),
    ]
