# Generated by Django 5.2.4 on 2025-09-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_inventory_branch_inventoryhistory'),
        ('dashbord_app', '0017_bankaccount_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord_app.invoice', verbose_name='فاکتور'),
        ),
    ]
