# Generated by Django 5.2.4 on 2025-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_inventorycount_barcode_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='نام کالا')),
                ('highest_purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='بالاترین قیمت خرید')),
                ('invoice_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ فاکتور')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فاکتور')),
                ('adjustment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تعدیل قیمت خرید')),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت معیار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'قیمت\u200cگذاری محصول',
                'verbose_name_plural': 'قیمت\u200cگذاری محصولات',
            },
        ),
    ]
