# Generated by Django 5.2.4 on 2025-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_inventoryhistory_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فروشنده')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='موبایل')),
                ('economic_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
            ],
        ),
    ]
