# Generated by Django 5.2.4 on 2025-09-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='invoice',
        ),
    ]
