# Generated by Django 5.2.4 on 2025-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_productpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت فروش'),
        ),
    ]
