# Generated by Django 5.2.4 on 2025-09-03 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_delete_seller_remove_inventoryhistory_invoice'),
        ('cantact_app', '0009_branch_branchadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='to_branch',
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('is_new', models.BooleanField(default=True, verbose_name='کالای جدید')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('count_date', models.CharField(max_length=10, verbose_name='تاریخ شمارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شمارنده')),
            ],
            options={
                'verbose_name': 'شمارش انبار',
                'verbose_name_plural': 'شمارش های انبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryHistory',
        ),
    ]
