# Generated by Django 5.2.4 on 2025-09-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_inventorycount_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='درصد سود'),
        ),
    ]
