# Generated by Django 5.2.4 on 2025-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_remove_inventoryhistory_from_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='count_date',
            field=models.CharField(default='', max_length=10, verbose_name='تاریخ شمارش'),
        ),
    ]
