# Generated by Django 5.2.4 on 2025-09-12 15:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_inventorycount_profit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='درصد سود'),
        ),
    ]
