# Generated by Django 5.2.4 on 2025-09-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_inventoryhistory_from_branch_and_more'),
        ('cantact_app', '0009_branch_branchadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='cantact_app.branch', verbose_name='از شعبه'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='cantact_app.branch', verbose_name='به شعبه'),
        ),
    ]
