# Generated by Django 5.2.4 on 2025-09-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_inventorycount_count_date'),
        ('account_app', '0007_alter_inventoryhistory_from_branch_and_more'),
    ]

    operations = [
    ]
