# Generated by Django 5.2.4 on 2025-09-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_inventorycount_profit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روش پرداخت')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتخوان'), ('bank', 'واریز به حساب'), ('cheque', 'چک')], max_length=10, verbose_name='نوع پرداخت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('terminal_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ترمینال')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('account_owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='صاحب حساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
