# Generated by Django 5.2.4 on 2025-09-13 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='شماره کارت باید 16 رقم باشد', regex='^[0-9]{16}$')], verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sheba_number', message='شماره شبا باید با IR شروع شده و 24 رقم داشته باشد', regex='^IR[0-9]{24}$')], verbose_name='شماره شبا'),
        ),
    ]
