# Generated by Django 5.2.4 on 2025-09-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_paymentmethod_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='quantity',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
    ]
