# Generated by Django 5.2.4 on 2025-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_alter_inventorycount_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='قیمت معیار'),
        ),
    ]
