# Generated by Django 5.2.4 on 2025-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_alter_productpricing_standard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت معیار'),
        ),
    ]
