# Generated by Django 5.2.4 on 2025-10-04 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_alter_productpricing_standard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='درصد سود'),
        ),
    ]
