# Generated by Django 5.2.4 on 2025-10-13 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0013_alter_inventorycount_profit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='درصد سود'),
        ),
    ]
