# Generated by Django 5.2.4 on 2025-10-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_alter_inventorycount_profit_percentage'),
        ('cantact_app', '0009_branch_branchadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cantact_app.branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='شمارنده'),
        ),
    ]
