# Generated by Django 5.2.4 on 2025-10-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_alter_inventorycount_branch_and_more'),
        ('cantact_app', '0009_branch_branchadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='شرح هزینه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ هزینه')),
                ('expense_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expense_receipts/', verbose_name='عکس فاکتور')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='compressed_receipts/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account_app.expense')),
            ],
            options={
                'verbose_name': 'عکس فاکتور',
                'verbose_name_plural': 'عکس\u200cهای فاکتور',
            },
        ),
    ]
