# Generated by Django 5.2.4 on 2025-10-17 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_expense_expenseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'عکس فاکتور', 'verbose_name_plural': 'عکس\u200cهای فاکتور'},
        ),
        migrations.AddField(
            model_name='expenseimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='expenseimage',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='compressed_receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expenseimage',
            name='image',
            field=models.ImageField(upload_to='expense_receipts/%Y/%m/%d/', verbose_name='عکس فاکتور'),
        ),
    ]
