# Generated by Django 5.2.4 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0017_alter_expenseimage_options_expenseimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='expense_receipts/%Y/%m/%d/', verbose_name='عکس فاکتور'),
        ),
    ]
