# Generated by Django 5.2.4 on 2025-10-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0018_alter_expenseimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت تایید'),
        ),
    ]
