# Generated by Django 5.2.4 on 2025-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0019_expense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
