# Generated by Django 5.2.4 on 2025-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0020_remove_expense_status_expense_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approved',
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت تایید'),
        ),
    ]
