# Generated by Django 5.2.4 on 2025-10-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0021_remove_expense_approved_expense_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت تایید'),
        ),
    ]
