# Generated by Django 5.2.4 on 2025-10-28 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0022_remove_expense_approval_status_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='درصد سود'),
        ),
    ]
